// This file is part of SaladSlicer. SaladSlicer is licensed 
// under the terms of GNU General Public License as published by the 
// Free Software Foundation. For more information and the LICENSE file, 
// see <https://github.com/3DCP-TUe/SaladSlicer>.

// System Libs
using System;
using System.Runtime.Serialization;
using System.Security.Permissions;
using Rhino.Geometry;

namespace SaladSlicer.Core.CodeGeneration
{
    /// <summary>
    /// Represents a custom (user definied) Code Line.
    /// </summary>
    public class AbsoluteCoordinate : IProgram
    {
        #region fields
        private Plane _plane;
        #endregion

        #region constructors
        /// <summary>
        /// Initializes an empty instance of the AbsoluteCoordinate class.
        /// </summary>         
        public AbsoluteCoordinate()
        {

        }
        /// <summary>
        /// Initializes a new instance of the AbsoluteCoordinate class.
        /// </summary>
        /// <param name="plane">Plane representing the origin of the point and optionally the direction (x-axis) of the movement</param>
        public AbsoluteCoordinate(Plane plane)
        {
            _plane = plane;
        }


        #endregion

        #region methods
        /// <summary>
        /// Returns a string that represents the current object.
        /// </summary>
        /// <returns> A string that represents the current object. </returns>
        public override string ToString()
        {
            return ($"X{_plane.OriginX:0.###} Y{_plane.OriginY:0.###} Z{_plane.OriginZ:0.###}");
        }

        /// <summary>
        /// Adds the NC program lines generated by this object to the program.
        /// </summary>
        /// <param name="programGenerator"> The program generator. </param>
        public void ToProgram(ProgramGenerator programGenerator)
        {
            programGenerator.Program.Add($"X{_plane.OriginX:0.###} Y{_plane.OriginY:0.###} Z{_plane.OriginZ:0.###}");
        }
        #endregion

        #region properties
        public bool IsValid
        {
            /// <summary>
            /// Gets a value indicating whether or not the object is valid.
            /// </summary>
            get
            { 
                if (_plane != null) { return false; } 
                return true;
            }
        }

        #endregion
    }
}
