// This file is part of SaladSlicer. SaladSlicer is licensed 
// under the terms of GNU General Public License as published by the 
// Free Software Foundation. For more information and the LICENSE file, 
// see <https://github.com/3DCP-TUe/SaladSlicer>.

namespace SaladSlicer.Core.CodeGeneration
{
    /// <summary>
    /// Represents the Feed Rate.
    /// </summary>
    public class FeedRate : IProgram
    {
        #region fields
        private double _feedRate;
        #endregion

        #region constructors
        /// <summary>
        /// Initializes an empty instance of the FeedRate class.
        /// </summary>         
        public FeedRate()
        {
            _feedRate = double.NaN;
        }

        /// <summary>
        /// Initializes a new instance of the FeedRate class.
        /// </summary>
        /// <param name="feedRate">Double representing the velocity of movement.</param>
        public FeedRate(double feedRate)
        {
            _feedRate = feedRate;
        }
        #endregion

        #region methods
        /// <summary>
        /// Returns a string that represents the current object.
        /// </summary>
        /// <returns> A string that represents the current object. </returns>
        public override string ToString()
        {
            return $"Set Feedrate (F{_feedRate:0.###} mm/min)";
        }

        /// <summary>
        /// Adds the NC program lines generated by this object to the program.
        /// </summary>
        /// <param name="programGenerator"> The program generator. </param>
        public void ToSinumerik(ProgramGenerator programGenerator)
        {
            programGenerator.Program.Add($"F{_feedRate:0.###} ; Feedrate in mm/min");
        }
        #endregion

        #region properties
        /// <summary>
        /// Gets a value indicating whether or not the object is valid.
        /// </summary>
        public bool IsValid
        {
            get
            { 
                if (_feedRate == double.NaN) { return false; } 
                return true;
            }
        }

        /// <summary>
        /// Gets or sets the feedrate in mm/min.
        /// </summary>
        public double Feedrate
        {
            get { return _feedRate; }
            set { _feedRate = value; }
        }
        #endregion
    }
}
