// This file is part of SaladSlicer. SaladSlicer is licensed 
// under the terms of GNU General Public License as published by the 
// Free Software Foundation. For more information and the LICENSE file, 
// see <https://github.com/3DCP-TUe/SaladSlicer>.

// System Libs
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Security.Permissions;
//Rhino Libs
using Rhino.Geometry;
// Salad Slicer Libs
using SaladSlicer.Utils;
using SaladSlicer.Interfaces;

namespace SaladSlicer.CodeGeneration
{
    /// <summary>
    /// Represents the Program Generator.
    /// </summary>
    [Serializable()]
    public class ProgramGenerator
    {
        #region fields
        private readonly List<string> _program = new List<string>();
        private ProgramSettings _programSettings = new ProgramSettings();
        #endregion

        #region constructors
        /// <summary>
        /// Initializes a new instance of the Program Generator class.
        /// </summary>
        public ProgramGenerator()
        {
        }
        #endregion

        #region methods
        /// <summary>
        /// Returns a string that represents the current object.
        /// </summary>
        /// <returns> A string that represents the current object. </returns>
        public override string ToString()
        {
            return "Program Generator";
        }

        /// <summary>
        /// Returns the G-code program as list with code lines.
        /// </summary>
        /// <param name="_objects"> The objects to gerenator the program for. </param>
        /// <returns> The program as a list with code lines. </returns>
        public List<string> CreateProgram(IList<IProgram> _objects)
        {
            _program.Clear();
            
            // Header
            _program.Add("; ----------------------------------------------------------------------");
            _program.Add("; This program was generated by Salad Slicer v" + HelperMethods.GetVersionNumber() + " (GPL v3).");
            _program.Add("; For more information visit https://github.com/3DCP-TUe/SaladSlicer.");
            _program.Add("; ----------------------------------------------------------------------");
            _program.Add(" ");

            // Program start settings
            //if (programType == 0)
            //{
            //    _program.Add("; ----------------------------------------------------------------------");
            //    _program.Add("; START SETTINGS");
            //    _program.Add("; ----------------------------------------------------------------------");
            //    _program.Add("G90; Absolute coordinates ");
            //    _program.Add("BSPLINE; Bspline interpolation") ;
            //    _program.Add("G642; Continuous-path mode with smoothing within the defined tolerances");
            //}
            //else if(programType == 1){
            //    _program.Add("; ----------------------------------------------------------------------");
            //    _program.Add("; START SETTINGS");
            //    _program.Add("; ----------------------------------------------------------------------");
            //    _program.Add("M106; Turn on fans");
            //    _program.Add("M201 X500.00 Y500.00 Z100.00 E5000.00; Setup machine max acceleration");
            //    _program.Add("M203 X500.00 Y500.00 Z10.00 E50.00; Setup machine max feedrate");
            //    _program.Add("M204 P500.00 R1000.00 T500.00; Setup Print/ Retract / Travel acceleration");
            //    _program.Add("M205 X8.00 Y8.00 Z0.40 E5.00; Setup Jerk");
            //    _program.Add("M82 ; absolute extrusion mode");
            //    _program.Add("G90; Absolute coordinates ");
            //    _program.Add("G1; Linear movements ");
            //    _program.Add("G28; Move home");
            //   }

            // Set program settings
            if (_objects[0].GetType() != typeof(ProgramSettings))
            {
                _program.Add("; ----------------------------------------------------------------------");
                _program.Add("; SETTINGS");
                _program.Add("; ----------------------------------------------------------------------");
                _program.Add(" ");
                _program.Add("; NO PROGRAM SETTINGS DEFINED");
                _program.Add("; Defaults settings are used");
                _program.Add(" ");

                ProgramSettings programSettings = new ProgramSettings();
                programSettings.ToProgram(this);
            }

            // G-code of different objects
            for (int i = 0; i < _objects.Count; i++)
            {
                _objects[i].ToProgram(this);
            }
            
            // Footer (ending)
            if (_programSettings.ProgramType == 0){
                _program.Add(" ");
                _program.Add("M30");
                _program.Add(" ");
                _program.Add(" ");
                _program.Add(" ");
            }
            else if (_programSettings.ProgramType == 1)
            {
                _program.Add(" ");
                _program.Add("G91; Relative coordinates ");
                _program.Add("Z10 E-2; Move off object and retract extrusion material ");
                _program.Add("G90; Absolute coordinates ");
                _program.Add("G28; Move home ");

                if (_programSettings.HotEndTemperature != 0 || _programSettings.BedTemperature != 0)
                {
                    if (_programSettings.HotEndTemperature >= 0)
                    {
                        _programSettings.HotEndTemperature = 0;
                        _program.Add($"M109 R{_programSettings.HotEndTemperature:0.#}; Set and wait for hotend temperature to 0");
                        _program.Add("M105; Report temperature");
                    }

                    if (_programSettings.BedTemperature >= 0)
                    {
                        _programSettings.BedTemperature = 0;
                        _program.Add($"M190 R{_programSettings.BedTemperature:0.#}; Set and wait for bed temperature to 0");
                        _program.Add("M105; Report temperature");
                    }
                }

                _program.Add("M106 S0; Turn off fan");
                _program.Add(" ");
            }

            return _program;
        }

        /// <summary>
        /// Adds a default pre-defined slicer header.
        /// </summary>
        /// <param name="name"> The object name. </param>
        /// <param name="layers"> The number of layers of the pre-defined slicer. </param>
        /// <param name="length"> The path length in mm. </param>
        public void AddSlicerHeader(string name, int layers, double length)
        {
            _program.Add(" ");
            _program.Add("; ----------------------------------------------------------------------");
            _program.Add($"; {name} - {layers:0} LAYERS - {(length / 1000):0.###} METER");
            _program.Add("; ----------------------------------------------------------------------");
            _program.Add(" ");
        }

        /// <summary>
        /// Adds a default pre-defined slicer header.
        /// </summary>
        /// <param name="name"> The object name. </param>
        /// <param name="length"> The path length in mm. </param>
        public void AddSlicerHeader(string name, double length)
        {
            _program.Add(" ");
            _program.Add("; ----------------------------------------------------------------------");
            _program.Add($"; {name} - {(length / 1000):0.###} METER");
            _program.Add("; ----------------------------------------------------------------------");
            _program.Add(" ");
        }

        /// <summary>
        /// Adds a default footer.
        /// </summary>
        public void AddFooter()
        {
            _program.Add(" ");
            _program.Add("; ----------------------------------------------------------------------");
            _program.Add(" ");
        }

        /// <summary>
        /// Returns the coordinate code lines including the added variables from an AddVariable instance.
        /// </summary>
        /// <param name="addVariable"> The added variable object to get the coorindate code lines from. </param>
        /// <returns> The nested list code lines. </returns>
        public static List<List<string>> GetCoordinateCodeLines(IAddVariable addVariable)
        {
            List<List<string>> result = new List<List<string>>();
            List<List<Plane>> frames = addVariable.FramesByLayer;

            // Coordinates
            for (int i = 0; i < frames.Count; i++)
            {
                List<string> temp = new List<string>() { };

                for (int j = 0; j < frames[i].Count; j++)
                {
                    temp.Add($"X{frames[i][j].OriginX:0.###} Y{frames[i][j].OriginY:0.###} Z{frames[i][j].OriginZ:0.###}");
                }

                result.Add(temp);
            }

            // Added variables
            foreach (KeyValuePair<string, List<List<double>>> entry in addVariable.AddedVariables)
            {
                for (int i = 0; i < result.Count; i++)
                {
                    for (int j = 0; j < result[i].Count; j++)
                    {
                        result[i][j] = result[i][j] + $" {entry.Key}{entry.Value[i][j]:0.###}";
                    }
                }
            }

            return result;
        }
        #endregion

        #region properties
        /// <summary>
        /// Gets a value indicating whether or not the object is valid.
        /// </summary>
        public bool IsValid
        {
            get
            {
                if (_program == null) { return false; }
                return true;
            }
        }

        /// <summary>
        /// Gets the list with program code lines.
        /// </summary>
        public List<string> Program
        {
            get { return _program; }
        }

        /// <summary>
        /// Gets or sets the program settings.
        /// </summary>
        public ProgramSettings ProgramSettings
        {
            get { return _programSettings; }
            set { _programSettings = value; }
        }
        #endregion 
    }
}
